[package]
name = "create-tag-rust"
version = "0.1.0"
authors = ["cottet.julien <julien.cottet@earthcube.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
